on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: "us-east-2"
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        app-name: [solar-wind-api]
        deployment-group-name: [solar-wind-app-main]
        repo: ['yakcmxela/solar-wind-api']
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::393694485536:role/GithubActions
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Create CodeDeploy Deployment
        id: deploy
        run: | 
          aws deploy create-deployment \ 
          --application-name solar-wind-api \ 
          --deployment-group-name solar-wind-app-main \ 
          --deployment-config-name CodeDeployDefault.AllAtOnce \ 
          --description "Deploying ${{ matrix.app-name }}-${{ github.sha }}" \ 
          --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
